version: '3.9'

services:

  postgresql:
    image: docker.io/bitnami/postgresql:16
    ports:
      - "5432:5432"
    volumes:
      - "postgresql_data:/bitnami/postgresql"
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=Rodibaba@1
      - POSTGRESQL_DATABASE=stoktakip





volumes:
  postgresql_data:
    driver: local

